title: CV | A jekyll template
description:  A beautiful template for your CV.
url: https://jekyll-cv.stavrospanakakis.com
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - preview.png
  - LICENSE
