title: CV
description: >
  The personal and professional portfolio of Thomas Neuenschwander, 
  a Computer Scientist, Co-founder, and technical leader passionate 
  about building solutions with technology.
url: https://thomneuenschwander.github.io
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - preview.png
  - LICENSE
